### ISSUE TITLE
suggestion for improvement / feature request

### ISSUE THREAD

**Issue by linuxbastler** [gedzeppelin/monitor-window-switcher#1]
I have one suggestion for improvement:

Please add the option to show all open windows in alt-tab,
not only the ones on the current monitor.
I achieved this by commenting out this line:
//    AltTab.getWindows = this.getWindows;

**Comment by gedzeppelin** [comment]
Hello, altough this was the desired behavior, I can add it as an option in the extension settings in the next days.

**Comment by gedzeppelin** [comment]
Implemented in https://github.com/gedzeppelin/monitor-window-switcher/commit/53611e80329a4f0285a6dc8d36103eed5cd7bbe2, can be achieved in the extensions preferences dialog. Awaiting approval in extensions page.
