### ISSUE TITLE
Super+Tab on current monitor

### ISSUE THREAD

**Issue by lepa22** [gedzeppelin/monitor-window-switcher#2]
Essentially, could you do the same for <kbd>Super</kbd>+<kbd>Tab</kbd>, so it would appear on the current monitor instead of the primary?

**Comment by lepa22** [comment]
The difference is that the _Monitor window switcher_ extension allows for having the switcher displayed on the monitor with the mouse while also showing windows from all monitors. The _Current screen only on window switcher_ extension only shows windows from the monitor with the, as the name suggests.

The _Monitor window switcher_ extension also supports versions from GNOME 3.34 to GNOME 40, whereas, as you mention, _Current screen only on window switcher_ only supports up to GNOME 3.32. The fact that it still works for the versions you mention is just a coincidence.

**Comment by leogama** [comment]
> The difference is that the _Monitor window switcher_ extension allows for having the switcher displayed on the monitor with the mouse while also showing windows from all monitors. The _Current screen only on window switcher_ extension only shows windows from the monitor with the, as the name suggests.

Thank you, @lepa22. Maybe this should be added in the README for clarification?

I think I'll give it a try! 😉

**Comment by lepa22** [comment]
It is indeed an optional feature. Please see this issue:
https://github.com/gedzeppelin/monitor-window-switcher/issues/1

**Comment by gedzeppelin** [comment]
Hello, sorry for the big delay, application switcher (Alt+Tab) support implemented in 1478688e5303b731023522ffbc9e8d780711e6fd, can be customized in the extensions preferences dialog in the same way the window switcher (Ctrl+Tab) does.

> > The difference is that the _Monitor window switcher_ extension allows for having the switcher displayed on the monitor with the mouse while also showing windows from all monitors. The _Current screen only on window switcher_ extension only shows windows from the monitor with the, as the name suggests.
> 
> Thank you, @lepa22. Maybe this should be added in the README for clarification? Currently it says quite the opposite:
> 
> > Filter windows by the monitor they are open on (instead of windows opened in all monitors).
> 
> Is it an optional feature? Anyway, I think I'll give it a try! wink

In addition, README was updated too.

**Comment by lepa22** [comment]
Thank you! Works as expected! :)
