### ISSUE TITLE
"settings is null" error from time to time

### ISSUE THREAD

**Issue by victornoel** [gedzeppelin/monitor-window-switcher#6]
Hi,

From time to time, I find out that the extension gets disabled because it has the error "settings is null" (according to extensions app from Gnome).

I'm not sure if there is a way to retrieve a more complete stacktrace of the error, but with instructions I should be able to share the details :)

Cheers

**Comment by victornoel** [comment]
Note: restarting Gnome Shell fixes the problem.

**Comment by gedzeppelin** [comment]
It should be fixed in c11b944e5f863498ccfa4fa81263e629050b7846, now live in GNOME extensions webpage.
